# Generated by Django 3.2.8 on 2024-01-20 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('web_site', models.URLField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=250)),
                ('city', models.CharField(default=None, max_length=150)),
                ('state', models.CharField(default=None, max_length=150)),
                ('country', models.CharField(default=None, max_length=150)),
                ('description', models.CharField(default=None, max_length=500)),
                ('property_Type', models.CharField(choices=[('Local', 'Local'), ('Apartamento', 'Apartamento'), ('Casa', 'Casa'), ('Finca', 'Finca'), ('Lote', 'Lote'), ('Otro', 'Otro')], default=None, max_length=20)),
                ('bedrooms', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('USD', 'Dólares estadounidenses'), ('EUR', 'Euros'), ('COP', 'Pesos colombianos')], default='USD', max_length=3)),
                ('garage', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default=None, max_length=20)),
                ('built_up_area_square_meters', models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_area_square_meters', models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.CharField(max_length=900)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
