# Generated by Django 3.2.8 on 2024-01-20 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appyhouselist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='Appyhouselist_app.company'),
            preserve_default=False,
        ),
    ]
