# Generated by Django 3.2.8 on 2024-01-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appyhouselist_app', '0004_comment_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='avg_qualification',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='number_qualification',
            field=models.IntegerField(default=0),
        ),
    ]
